waysact/webpack-subresource-integrity

README.md
A very small addition on the README.
=> Update README to add contribution guidelines

.codeclimate.yml, LICENSE, README.md, index.js, package.json, test/dummy.js, test/test-webpack.js
Also updated docs. 
With this change, anyone using html-webpack-plugin will get integrity attributes added to their script tags. 
Also bumped revision number. 
This also addresses issue #3
=> Direct support for html-webpack-plugin courtesy of a nice hook they added

.travis.yml, README.md, index.js, test/chunk2.js, test/test-webpack.js
=> Don't remove directory from asset path

.travis.yml, appveyor.yml, package.json
- Test all supported Node versions in combination with both supported Webpack versions on both Travis and Appveyor
- Set correct minimum Node version (0.12) in package.json
=> CI completeness

.travis.yml, package.json
Also fix timeout setting for Travis builds.
=> Increase mocha timeout to 20s

.eslintignore, .travis.yml, README.md, appveyor.yml, karma.conf.js, package.json, test/test-webpack.js
Test coverage to 100%, and various small improvements (see commits).
=> Test coverage to 100% and various small improvements 

index.js, package.json, test/test-webpack.js
=> Prevent infinite recursion in findDepChunks

package.json
Upgrade to file-loader ^0.10.0
=> Upgrade dev dependencies

README.md, index.js, test/test-webpack.js
=> Clarify incompatibility with hot reloading

index.js, test/test-webpack.js
=> Fix invalid JavaScript generation with certain named chunk IDs

appveyor.yml, index.js, test/test-webpack.js
=> More robust path matching

.codeclimate.yml, index.js, test/test-webpack.js
=> Support multiple common chunks

index.js, test/test-misc.js
=> Better wording for crossOriginLoading warning

package.json
=> Make Puppeteer a dev dependency

LICENSE, README.md, index.js, jmtp.js, test/defaultCheck.js, test/test-examples.js, test/test-misc.js, util.js
Also add copyright notices into core files.
=> Change copyright to last until present

.travis.yml, README.md, appveyor.yml, examples/warn-checksum/test.js, examples/webpack4-contenthash/README.md, examples/webpack4-contenthash/chunk.js, examples/webpack4-contenthash/index.js, examples/webpack4-contenthash/test.js, examples/webpack4-contenthash/webpack.config.js, index.js, jmtp.js, package.json, util.js
- Fix incompatibility with Webpack 4.13+, the `crossOrigin` attribute wasn't set correctly
- Fix coverage reporting to include all builds
- Fix incompatibility with Webpack 4.3+ `contenthash` placeholder. #78 
- Tentative compatibility with upcoming html-webpack-plugin 4. #80
=> Various overdue improvements

examples/webpack4-contenthash-issue-83/README.md, examples/webpack4-contenthash-issue-83/chunk.js, examples/webpack4-contenthash-issue-83/index.css, examples/webpack4-contenthash-issue-83/index.js, examples/webpack4-contenthash-issue-83/test.js, examples/webpack4-contenthash-issue-83/webpack.config.js, index.js, util.js
=> Record chunk assets through hook

examples/non-web-build/README.md, examples/non-web-build/test.js, examples/non-web-build/webpack.config.js, jmtp.js
=> Fix crash in non-web builds, emit warning instead

README.md, examples/hwp-externals/README.md, examples/hwp-externals/index.js, examples/hwp-externals/test.js, examples/hwp-externals/webpack.config.js, index.js, package.json
=> Ensure we work with HtmlWebpackExternalsPlugin

package.json
=> Mark html-webpack-plugin as an optional peer

examples/minimal-sri-hashes/README.md, examples/minimal-sri-hashes/index.js, examples/minimal-sri-hashes/lazy.js, examples/minimal-sri-hashes/test.js, examples/minimal-sri-hashes/webpack.config.js, jmtp.js
=> Ensure no superfluous SRI hashes are included

.travis.yml, package.json
Ref https://stackoverflow.com/questions/55674746/travis-sh-0-cant-open-etc-init-d-xvfb
=> Attempt at fixing Travis build issue

README.md
=> Warn about unreliable <link preload> in README

examples/issue-147/README.md, examples/issue-147/async.js, examples/issue-147/index.js, examples/issue-147/package.json, examples/issue-147/webpack.config.js, webpack-subresource-integrity/index.ts, yarn.lock
=> Fix error when processing tag with no attributes

examples/issue-221/index.js, examples/issue-221/package.json, examples/issue-221/webpack.config.js, webpack-subresource-integrity/src/plugin.ts, yarn.lock
=> Fix issue with percent encoded filenames
